### ISSUE TITLE
IOError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by dtouzeau** [Janhouse/tespeed#22]
Always finish with crash

IP: 109.15.153.228; Lat: 48.900000; Lon: 2.333300; ISP: SFR
Loading server list...
Looking for closest and best server...
Testing latency...
2559 ms latency for http://speedtest1.proxad.net/speedtest/ (FreeMobile, Paris, France) [3.24 km]
2571 ms latency for http://www.groupe-mediactive.fr/speedtest/speedtest/ (MEDIACTIVE, Paris, France) [3.24 km]
2564 ms latency for http://orangemesure02.ikoula.com/speedtest/ (Orange France, Paris, France) [3.24 km]
2714 ms latency for http://speedtest.sfrbusinessteam.fr/speedtest/ (SFR, Paris, France) [3.24 km]
2703 ms latency for http://speedtest.lafibre.info/speedtest/ (Bouygues Telecom, Paris, France) [3.24 km]
Traceback (most recent call last):
  File "/root/tespeed/tespeed.py", line 661, in <module>
    main(args)
  File "/root/tespeed/tespeed.py", line 636, in main
    chunksize=args.chunksize
  File "/root/tespeed/tespeed.py", line 148, in __init__
    self.TestSpeed()
  File "/root/tespeed/tespeed.py", line 586, in TestSpeed
    self.TestDownload()
  File "/root/tespeed/tespeed.py", line 552, in TestDownload
    sizes, took=self.AsyncRequest(url, thrds )
  File "/root/tespeed/tespeed.py", line 426, in AsyncRequest
    d=Manager().dict()
  File "/usr/lib/python2.6/multiprocessing/managers.py", line 634, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python2.6/multiprocessing/managers.py", line 532, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python2.6/multiprocessing/connection.py", line 149, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python2.6/multiprocessing/connection.py", line 383, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
IOError: [Errno 11] Resource temporarily unavailable

**Comment by Janhouse** [comment]
Closing this issue. If you still get it - please reopen.
