### ISSUE TITLE
IOError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by lin2online** [Janhouse/tespeed#23]
Testing latency...
36 ms latency for http://www.catspeedtest.net/mini/speedtest/ (cattelecom, Bangkok, Thailand) [2.01 km]
7 ms latency for http://speedtest1.sbn-idc.net/speedmini/speedtest/ (SBN, Bangkok, Thailand) [2.01 km]
5 ms latency for http://61.91.246.158/speedtest/ (STS Group, Bangkok, Thailand) [2.01 km]
7 ms latency for http://speedtest1.dtacnetwork.com/speedtest/ (dtac trinet, Bangkok, Thailand) [2.01 km]
6 ms latency for http://speedtest.gxpnetwork.com/speedtest/ (GamerXP Network, Bangkok, Thailand) [2.01 km]
Traceback (most recent call last):
  File "./tespeed.py", line 662, in <module>
    main(args)
  File "./tespeed.py", line 637, in main
    chunksize=args.chunksize
  File "./tespeed.py", line 149, in __init__
    self.TestSpeed()
  File "./tespeed.py", line 587, in TestSpeed
    self.TestDownload()
  File "./tespeed.py", line 553, in TestDownload
    sizes, took=self.AsyncRequest(url, thrds )
  File "./tespeed.py", line 427, in AsyncRequest
    d=Manager().dict()
  File "/usr/lib/python2.6/multiprocessing/managers.py", line 634, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python2.6/multiprocessing/managers.py", line 532, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python2.6/multiprocessing/connection.py", line 149, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python2.6/multiprocessing/connection.py", line 383, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
IOError: [Errno 11] Resource temporarily unavailable

help me please

**Comment by Janhouse** [comment]
duplicate of #22
