### ISSUE TITLE
lxml.etree.XMLSyntaxError: Start tag expected

### ISSUE THREAD

**Issue by Choromanski** [Janhouse/tespeed#42]
I am getting an error with etree

```
Traceback (most recent call last):                                                                                                                                           
  File "./tespeed.py", line 720, in <module>
    main(args)
  File "./tespeed.py", line 691, in main
    uploadtests=args.uploadtests, 
  File "./tespeed.py", line 156, in __init__
    self.TestSpeed()
  File "./tespeed.py", line 632, in TestSpeed
    self.server_list=self.LoadServers()
  File "./tespeed.py", line 411, in LoadServers
    servers_xml = etree.fromstring(response.read())
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring                                                                                                             
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument                                                                                                  
  File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc                                                                                                             
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc                                                                                                 
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc                                                                                   
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult                                                                                                     
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError                                                                                                       
  File "<string>", line 1                                                                                                                                                    
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```

Will work on a fix for this

**Comment by 001101** [comment]
me2

archlinux - Python 2.7.16 - python-argparse & python2-lxml installed

**Comment by shuish0071** [comment]
me2

**Comment by sackio** [comment]
me2

**Comment by drsandro** [comment]
Hi,

I forked the project and fixed it. The response is using gzip now, so it didn't work anymore. 

https://github.com/drsandro/tespeed
